### ISSUE TITLE
Add "dismiss" button to metering notification

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amp-publisher-sample#26]
For demo purposes, could you please add "Dismiss" button to the metering notification?

**Comment by andreban** [comment]
Do you mean something like the screenshot below?
<img width="335" alt="screen shot 2016-02-02 at 3 15 30 pm" src="https://cloud.githubusercontent.com/assets/1733592/12753647/e074fdfa-c9bf-11e5-8816-0dbea0c748da.png">

**Comment by dvoytenko** [comment]
Exactly. Is it already done? :)
