### ISSUE TITLE
Ensure that the CORS Security protocol is fully implemented

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amp-publisher-sample#30]
Blocked currently on https://github.com/ampproject/amphtml/pull/1773 and https://github.com/ampproject/amphtml/pull/1772 but they should be submitted today.

The described protocol should be fully implemented for reference implementation.

**Comment by sebastianbenz** [comment]
@dvoytenko I think we can close this or is there something missing?

**Comment by dvoytenko** [comment]
All good!
