### ISSUE TITLE
Add analytics examples to access pages

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amp-publisher-sample#37]
/cc @sebastianbenz @rudygalfi 

The new analytics integration for AMP Access has been submitted. It's now available under the experiment. See for more info: https://github.com/ampproject/amphtml/blob/master/extensions/amp-access/amp-access-analytics.md

It'd be great to have (however minimal but realistic) example of this integration in our sample publisher.

**Comment by andreban** [comment]
Closed by #42
