### ISSUE TITLE
React based sample and AMP Validator

### ISSUE THREAD

**Issue by JosefJezek** [ampproject/amp-publisher-sample#64]
AMP Validator don't see AMP content in React based sample.

https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc

**Comment by sebastianbenz** [comment]
Yes - that's working as intended. The validator requires the root document to be AMPHTML.

**Comment by JosefJezek** [comment]
@sebastianbenz Do Google Search see AMP content in Shadow DOM?

**Comment by andreban** [comment]
When the service-worker is not installed, the user will be served the AMP version of the page, which is correctly validated by the AMP validator:

<img width="404" alt="screen shot 2017-02-06 at 9 39 27 am" src="https://cloud.githubusercontent.com/assets/1733592/22643654/4b26d960-ec57-11e6-9acc-c849dab84658.png">

Once the service worker is installed, the request is caught by it and the app-shell is served. The app-shell itself is not an AMP page. It fetches the correspondent AMP page and uses the amp-shadow element to render it inside the shell. 

So, whenever a user-agent sees the page for the first time, the AMP version is served. The AMP version will also be served when the user-agent does not support service-workers.

**Comment by JosefJezek** [comment]
@andreban Service Worker is awesome. Thank you
