### ISSUE TITLE
Issue with AMP Access server examples

### ISSUE THREAD

**Issue by edhollinghurst** [ampproject/amp-publisher-sample#94]
I'm seeing the following error when trying to view the AMP Access server examples.

```
log.js:162 Authorization failed:  SyntaxError: Unexpected token e in JSON at position 0
    at amp-access-client.js:128
    at <anonymous>
```
Steps to reproduce:
1. Enable 'amp-access-jwt' and 'amp-access-server' at https://cdn.ampproject.org/experiments.html
2. `git clone git@github.com:ampproject/amp-publisher-sample.git`
3. `cd amp-paywall-demo`
4. `npm install`
5. `npm start`
6. Visit http://localhost:8002/amp-access/sample/server/0
7. Observe error in console.

Any help with how to resolve this issue would be appreciated.

**Comment by andreban** [comment]
Hi Ed,

1. Can you try visiting the page at http://localhost:8002/amp-access/sample/server/0
2. Open the browser console and enable the experiments. with `AMP.toggleExperiment`
```
AMP.toggleExperiment('amp-access-server');
AMP.toggleExperiment('amp-access-jwt');
```
3. Ensure that `true` is printed on the console for both commands.
4. Reload the page.

**Comment by edhollinghurst** [comment]
OK all good now - thanks Andre!
