### ISSUE TITLE
[amp-pwa-reader]: articles not loading offline

### ISSUE THREAD

**Issue by DavidScales** [ampproject/amp-publisher-sample#98]
In Chrome 65, the images & runtime cache assets aren't being cached, apparently due to a quota exceeded error:

<img width="851" alt="screen shot 2018-04-13 at 1 13 05 pm" src="https://user-images.githubusercontent.com/16726377/38756011-cc423850-3f1c-11e8-86a9-0c29c8df5d92.png">

As a result, only the pre-cached files are loading offline, so the user gets basically en empty app shell.

In Firefox, images & runtime caches are populating. The home page appears to load offline, but previously visited articles don't (assuming thats intended functionality). There are no errors logged, just a stalled loading icon.

**Comment by DavidScales** [comment]
Ah, so I see that this is because incognito tabs don't allow more than a certain amount of storage, which I was unaware of. Using non-incognito Chrome resolves the Quote exception issue and allows assets to cache. 

However, previously visited articles are still not viewable offline in either Chrome or Firefox.

**Comment by pbakaus** [comment]
hi @DavidScales, offline is never a feature we supported :) The SW is mainly used to give a speed up right now. But graceful handling of flaky connections would sure be nice. PRs welcome.

**Comment by DavidScales** [comment]
Ah okay, my mistake. Thanks for your response. If I get some free time at some point I will take a look at it :)
